---
driver:
  name: vagrant
  network:
    - ['private_network', {ip: '192.168.34.34'}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[security_guide::default]
    attributes:
